openapi: 3.0.0
info:
  title: Express API MongoDB Customers
  description: API para gerenciar clientes usando Express e MongoDB
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Servidor local

paths:
  /customers:
    get:
      summary: Lista todos os clientes
      responses:
        "200":
          description: Lista de clientes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"
    post:
      summary: Cria um novo cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
      responses:
        "201":
          description: Cliente criado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"

  /customers/{id}:
    get:
      summary: Obtém um cliente pelo ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Cliente encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        "404":
          description: Cliente não encontrado
    put:
      summary: Atualiza um cliente pelo ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
      responses:
        "200":
          description: Cliente atualizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        "404":
          description: Cliente não encontrado
    delete:
      summary: Deleta um cliente pelo ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Cliente deletado
        "404":
          description: Cliente não encontrado

components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        phone:
          type: string
